### ISSUE TITLE
Disabling frequency discrepancy check causes error

### ISSUE THREAD

**Issue by babak-ra** [bvilhjal/ldpred#60]
When `--max-freq-discrep 1` is used, the code throws the following error, which appears to be caused since `num_freq_discrep_filtered_snps` is not set when discrepancy is not checked.

```
Traceback (most recent call last):
  File "./LDpred.py", line 271, in <module>
    main()
  File "./LDpred.py", line 256, in main
    coord_genotypes.main(p_dict)
  File "/opt/ldpred-1.0.2/ldpred/coord_genotypes.py", line 563, in main
    debug=p_dict['debug'])
  File "/opt/ldpred-1.0.2/ldpred/coord_genotypes.py", line 496, in coordinate_datasets
    tot_num_freq_discrep_filtered_snps += num_freq_discrep_filtered_snps
UnboundLocalError: local variable 'num_freq_discrep_filtered_snps' referenced before assignment
```

**Comment by babak-ra** [comment]
I should also add even when not providing `--reffreq` in `CUSTOM` format, SNPs are filtered out due to frequency discrepancy.

**Comment by bvilhjal** [comment]
Hi, thanks for the bug report!  I also noticed that the max-discrep doesn't work, I have fixed it on the develop branch, and will merge it to the master branch and make a new release later today.  I'm also fixing another bug.

Cheers,
Bjarni

**Comment by bvilhjal** [comment]
fixed now in v. 1.0.3

**Comment by babak-ra** [comment]
Thanks for the update. I still get the same error when  `--max-freq-discrep 1`:

```
Traceback (most recent call last):   
  File "./LDpred.py", line 274, in <module>  
    main()             
  File "./LDpred.py", line 259, in main       
    coord_genotypes.main(p_dict)         
  File "/opt/ldpred-1.0.3/ldpred/coord_genotypes.py", line 559, in main  
    debug=p_dict['debug']) 
  File "/opt/ldpred-1.0.3/ldpred/coord_genotypes.py", line 493, in coordinate_datasets     
    tot_num_freq_discrep_filtered_snps += num_freq_discrep_filtered_snps
```

**Comment by bvilhjal** [comment]
Oh no, I somehow seemed to created a new error when fixing the other.  I committed the fix on master now.  Will test today before making a new release.

Cheers,
Bjarni

**Comment by namjoub2** [comment]
what does 1 mean here 100% discrepancy  or 1% discrepancy?
