### ISSUE TITLE
Recognizing X chromosome, "Unable to open object (object 'chrom_23' doesn't exist)"

### ISSUE THREAD

**Issue by Ambrosinae** [bvilhjal/ldpred#66]
Hi,

I looked at the previous issue brought up about the final chromosome here: https://github.com/bvilhjal/ldpred/issues/17 and it seems that ldpred should be able to recognize X as a valid chromosome with the most up-to-date version. However, I am getting this error during the coordination step:

`"Unable to open object (object 'chrom_23' doesn't exist)"

Did not find chromosome in SS dataset.`

And later in the 'Summary of Coordination Step' section:

`Num chromosomes used:                                                         22`

Both my plink files and SS file should have the chromosome listed as a capital X. I am using the most recent version of ldpred in the master branch.

Best,
Josh

**Comment by bvilhjal** [comment]
I believe I've fixed this now.  Thanks for reporting.  Let me know if you have any problems with the fix.  It should also be easy to extend to other chromosomes (Y, MT), but I'm worried about how the SNPs are coded for those, hence I didn't want to extend it for those now.

Best,
Bjarni

**Comment by Ambrosinae** [comment]
Hi,

I still have this error.

`"Unable to open object (object 'chrom_23' doesn't exist)"

Did not find chromosome 23 in SS dataset.

Continuing.`

`SNPs in LD Reference data:                                              12066678

Num chromosomes used:                                                         22

SNPs common across datasets:                                            11740250`

Best,
Josh

**Comment by bvilhjal** [comment]
Hi, I thought I had fixed it.  Will look at later this week.  I'm sorry about this.

Best,
Bjarni

**Comment by Ambrosinae** [comment]
It's no problem, everything still works if I just remove chr23 from the files.

Josh

**Comment by bvilhjal** [comment]
I believe parsing and working with X chromosomes already works, so I'll close this.
